version: '3'

services:
    db:
        image: postgres:latest
        hostname: db
        environment:
            - POSTGRES_PASSWORD=123
            - POSTGRES_USER=postgres
            - POSTGRES_DB=conecta_uni
        ports:
            - '5432:5432'
        command: postgres -c checkpoint_timeout=600 -c max_wal_size=2048
